remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
title: Curso de Automatizaciones
description: Material completo del curso de automatizaciones
markdown: kramdown
relative_links:
  enabled: true
  collections: true
show_downloads: false 